// 2026 新版沪教版（五四学制）英语 四年级上册 随堂知识点题库
// 教材：（根据2022年版课程标准修订）义务教育教科书（五•四学制）·英语四年级上册 · 上海教育出版社
// 目录（国家中小学智慧教育平台官方电子教材）：Starter + Unit 1 My school / Unit 2 My classmates
//       / Unit 3 Animals and their homes / Unit 4 Our birthday / Unit 5 Visiting places
//       / Unit 6 It's autumn! / Unit 7 My healthy breakfast / Unit 8 Be honest
//       / Unit 9 What time is it? / Unit 10 Weather
// Starter + 每个单元一关，每关 10 题，共 11 关 110 题

export type QType = 'choice' | 'judge'

export interface Question {
  id: string
  type: QType
  q: string
  options: string[]
  answer: number
  explain: string
  tag: string
}

export interface Unit {
  id: string
  name: string
  title: string
  emoji: string
  color: string
  lessons: string[]
  intro: string
}

export const UNITS: Unit[] = [
  {
    id: 'gst',
    name: '衔接关',
    title: 'Starter 热身站',
    emoji: '🌈',
    color: 'teal',
    lessons: ['Greetings 问候', 'Numbers & Colours 数字颜色', 'Days & Weather 星期天气'],
    intro: '热身开始！把问候语、数字、颜色和天气再复习一遍，大声说 English！',
  },
  {
    id: 'g1',
    name: '第一单元',
    title: 'My school',
    emoji: '🏫',
    color: 'orange',
    lessons: ['School places 学校场所', 'My favourite place 最喜欢的地方'],
    intro: 'library、hall、art room……校园里的地方你都会说了吗？一起来介绍我的学校！',
  },
  {
    id: 'g2',
    name: '第二单元',
    title: 'My classmates',
    emoji: '🧑‍🤝‍🧑',
    color: 'red',
    lessons: ['Describing people 描述同学', 'A guessing game 猜一猜'],
    intro: 'helpful、interesting、great……用英语夸夸你的同桌吧！',
  },
  {
    id: 'g3',
    name: '第三单元',
    title: 'Animals and their homes',
    emoji: '🐼',
    color: 'emerald',
    lessons: ['Animals in China 中国动物', 'Animal homes 动物的家'],
    intro: 'panda、elephant、polar bear……动物的家园在哪里？一起来守护它们！',
  },
  {
    id: 'g4',
    name: '第四单元',
    title: 'Our birthday',
    emoji: '🎂',
    color: 'rose',
    lessons: ['Birthday party 生日聚会', 'Letters of love 爱的信'],
    intro: 'invitation、noodles、share a cake——用英语策划一个温馨的生日会！',
  },
  {
    id: 'g5',
    name: '第五单元',
    title: 'Visiting places',
    emoji: '🗺️',
    color: 'sky',
    lessons: ['In my neighbourhood 社区', 'Visiting Venice 游水城'],
    intro: 'museum、cinema、supermarket……逛逛社区，用英语说说哪里好玩！',
  },
  {
    id: 'g6',
    name: '第六单元',
    title: "It's autumn!",
    emoji: '🍂',
    color: 'amber',
    lessons: ['Autumn days 秋天', 'Writing a poem 写小诗'],
    intro: 'Leaves fall, birds fly south——秋天藏着好多英语小秘密！',
  },
  {
    id: 'g7',
    name: '第七单元',
    title: 'My healthy breakfast',
    emoji: '🥣',
    color: 'lime',
    lessons: ['Breakfast food 早餐', 'A healthy menu 健康菜单'],
    intro: 'bread、milk、juice……早餐吃什么？健康早餐用英语点单！',
  },
  {
    id: 'g8',
    name: '第八单元',
    title: 'Be honest',
    emoji: '🤝',
    color: 'violet',
    lessons: ['Honest me 诚实的我', 'Keep your word 说到做到'],
    intro: 'tell the truth, never tell a lie——诚实是最棒的品质！',
  },
  {
    id: 'g9',
    name: '第九单元',
    title: 'What time is it?',
    emoji: '⏰',
    color: 'fuchsia',
    lessons: ['Time on the clock 钟表时间', 'A board game 时间棋盘'],
    intro: "o'clock、half past、ten to……看钟说时间，做时间小主人！",
  },
  {
    id: 'g10',
    name: '第十单元',
    title: 'Weather',
    emoji: '🌤️',
    color: 'cyan',
    lessons: ['Weather words 天气词', 'A weather report 天气预报'],
    intro: 'sunny、rainy、cloudy、snowy——像小主持人一样播天气吧！',
  },
]

export const QUESTIONS: Record<string, Question[]> = {
  gst: [
    {
      id: 'gstq1',
      type: 'choice',
      q: '早上见到老师，你应该说？',
      options: ['Good morning!', 'Good night!', 'Goodbye!', 'Thank you!'],
      answer: 0,
      explain: 'Good morning 是早上问好，中午用 Good afternoon，晚上用 Good evening。',
      tag: '问候语',
    },
    {
      id: 'gstq2',
      type: 'choice',
      q: '别人问你 How are you?，可以怎么回答？',
      options: ["I'm fine, thank you.", 'My name is Lily.', 'Goodbye!', 'Good night!'],
      answer: 0,
      explain: 'How are you? 问身体好不好，回答 I\'m fine, thank you.（我很好，谢谢）。',
      tag: '问候语',
    },
    {
      id: 'gstq3',
      type: 'choice',
      q: 'three ＋ two ＝ ?',
      options: ['five', 'four', 'six', 'ten'],
      answer: 0,
      explain: '3＋2＝5，five。数字 1-10：one two three four five six seven eight nine ten。',
      tag: '数字',
    },
    {
      id: 'gstq4',
      type: 'choice',
      q: '香蕉是什么颜色的？The banana is ______.',
      options: ['yellow', 'red', 'blue', 'black'],
      answer: 0,
      explain: '香蕉是黄色的，yellow。常见颜色：red 红、blue 蓝、green 绿、yellow 黄。',
      tag: '颜色',
    },
    {
      id: 'gstq5',
      type: 'choice',
      q: '一个星期有几天？',
      options: ['seven days', 'five days', 'ten days', 'six days'],
      answer: 0,
      explain: '一周有 7 天，seven days：Monday 到 Sunday。',
      tag: '星期',
    },
    {
      id: 'gstq6',
      type: 'choice',
      q: 'It is raining. （外面在下雨）你出门要带上？',
      options: ['an umbrella', 'sunglasses', 'a kite', 'a scarf'],
      answer: 0,
      explain: '下雨要带雨伞 umbrella。sunny 才需要太阳镜哦。',
      tag: '天气',
    },
    {
      id: 'gstq7',
      type: 'choice',
      q: '别人问 What\'s your name?，你应该回答？',
      options: ['My name is Shenshen.', "I'm fine.", 'Yes, it is.', 'Thank you.'],
      answer: 0,
      explain: 'What\'s your name? 问名字，回答 My name is … 或 I\'m …。',
      tag: '问候语',
    },
    {
      id: 'gstq8',
      type: 'judge',
      q: '「Good afternoon.」用于下午和别人打招呼。',
      options: ['对', '错'],
      answer: 0,
      explain: '对！afternoon 是下午，中午 12 点到傍晚都可以用 Good afternoon 问好。',
      tag: '问候语',
    },
    {
      id: 'gstq9',
      type: 'choice',
      q: 'nine 后面接着数是哪个数字？',
      options: ['ten', 'eight', 'seven', 'eleven'],
      answer: 0,
      explain: '按顺序 eight, nine, ten——nine 后面是 ten（10）。',
      tag: '数字',
    },
    {
      id: 'gstq10',
      type: 'choice',
      q: '「umbrella」是什么意思？',
      options: ['雨伞', '大衣', '鞋子', '帽子'],
      answer: 0,
      explain: 'umbrella＝雨伞，下雨时带上它就不怕淋湿啦。',
      tag: '天气',
    },
  ],
  g1: [
    {
      id: 'g1q1',
      type: 'choice',
      q: '想看书、借书，应该去学校的哪里？',
      options: ['library', 'canteen', 'gym', 'toilet'],
      answer: 0,
      explain: 'library 图书馆/图书室，里面有很多书可以看、可以借。',
      tag: '学校场所',
    },
    {
      id: 'g1q2',
      type: 'choice',
      q: '「sports field」是什么地方？',
      options: ['操场', '食堂', '电脑室', '教室'],
      answer: 0,
      explain: 'sports field 操场/运动场，We play football on the sports field. 我们在操场上踢足球。',
      tag: '学校场所',
    },
    {
      id: 'g1q3',
      type: 'choice',
      q: '在哪里可以上电脑课？',
      options: ['computer room', 'art room', 'hall', 'library'],
      answer: 0,
      explain: 'computer room 电脑室/机房。art room 是美术室，hall 是礼堂。',
      tag: '学校场所',
    },
    {
      id: 'g1q4',
      type: 'choice',
      q: 'We draw and paint in the ______. （我们画画的地方）',
      options: ['art room', 'sports field', 'canteen', 'toilet'],
      answer: 0,
      explain: 'draw and paint 画画，画画在美术室 art room。',
      tag: '学校场所',
    },
    {
      id: 'g1q5',
      type: 'choice',
      q: 'We have lessons in the ______.（我们上课的地方）',
      options: ['classroom', 'library', 'hall', 'garden'],
      answer: 0,
      explain: 'classroom 教室，是上课（have lessons）的地方。',
      tag: '学校场所',
    },
    {
      id: 'g1q6',
      type: 'choice',
      q: '全校开大会、演节目的地方是？',
      options: ['hall', 'classroom', 'computer room', 'sports field'],
      answer: 0,
      explain: 'hall 礼堂/大厅，可以全校集会、看演出。',
      tag: '学校场所',
    },
    {
      id: 'g1q7',
      type: 'choice',
      q: 'There ______ many books in the library. 括号里填？',
      options: ['are', 'is', 'am', 'be'],
      answer: 0,
      explain: 'books 是复数，There are many books. There be 句型就近看单复数。',
      tag: '句型',
    },
    {
      id: 'g1q8',
      type: 'choice',
      q: '「school building」指的是？',
      options: ['教学楼', '操场', '图书馆', '校车'],
      answer: 0,
      explain: 'school building 学校的建筑/教学楼，building 是建筑物。',
      tag: '单词',
    },
    {
      id: 'g1q9',
      type: 'judge',
      q: 'We eat lunch in the computer room. 这句话是对的。',
      options: ['对', '错'],
      answer: 1,
      explain: '错！吃午饭应该去食堂 canteen，不是电脑室。',
      tag: '常识判断',
    },
    {
      id: 'g1q10',
      type: 'choice',
      q: 'My favourite place in the school is the library, because I can ______.（为什么喜欢图书馆）',
      options: ['read many books', 'run fast', 'play games', 'eat snacks'],
      answer: 0,
      explain: '图书馆可以读很多书 read many books，这是喜欢图书馆的理由。',
      tag: '表达',
    },
  ],
  g2: [
    {
      id: 'g2q1',
      type: 'choice',
      q: '「helpful」是什么意思？',
      options: ['乐于助人的', '害羞的', '生气的', '累的'],
      answer: 0,
      explain: 'helpful＝乐于助人的（help 帮助＋ful），He is very helpful. 他很乐于助人。',
      tag: '形容词',
    },
    {
      id: 'g2q2',
      type: 'choice',
      q: '「interesting」的意思是？',
      options: ['有趣的', '无聊的', '强壮的', '安静的'],
      answer: 0,
      explain: 'interesting＝有趣的，an interesting story 一个有趣的故事。',
      tag: '形容词',
    },
    {
      id: 'g2q3',
      type: 'choice',
      q: 'She is a ______ girl. （形容小姑娘可爱）',
      options: ['lovely', 'help', 'run', 'jump'],
      answer: 0,
      explain: 'lovely＝可爱的，是形容词；这句需要形容词修饰名词 girl。',
      tag: '形容词',
    },
    {
      id: 'g2q4',
      type: 'choice',
      q: '「different」的意思是？',
      options: ['不同的', '相同的', '困难的', '简单的'],
      answer: 0,
      explain: 'different＝不同的，We are in different classes. 我们在不同的班级。',
      tag: '形容词',
    },
    {
      id: 'g2q5',
      type: 'choice',
      q: '「great」可以用来表达？',
      options: ['很棒的', '很差的', '很小的', '很慢的'],
      answer: 0,
      explain: 'great＝很棒的、极好的，You did a great job! 你做得太棒了！',
      tag: '形容词',
    },
    {
      id: 'g2q6',
      type: 'choice',
      q: '「Who is he?」的正确回答是？',
      options: ['He is my classmate.', 'She is ten.', 'It is a book.', 'I am fine.'],
      answer: 0,
      explain: 'Who is he? 问他是谁，回答 He is …；问女生才用 Who is she?',
      tag: '句型',
    },
    {
      id: 'g2q7',
      type: 'choice',
      q: '______ is she? — She is Minmin. 括号里填？',
      options: ['Who', 'What', 'Where', 'How'],
      answer: 0,
      explain: '回答是人名，用 Who 问「谁」。',
      tag: '句型',
    },
    {
      id: 'g2q8',
      type: 'choice',
      q: '「My classmates all like sports.」中「all」的意思是？',
      options: ['都', '只有', '不', '两个'],
      answer: 0,
      explain: 'all 表示「全部、都」：我的同学们都喜欢运动。',
      tag: '单词',
    },
    {
      id: 'g2q9',
      type: 'choice',
      q: '「different」的反义词是？',
      options: ['same', 'helpful', 'great', 'lovely'],
      answer: 0,
      explain: 'different 不同的 ↔ same 相同的，They are in the same school. 他们在同一所学校。',
      tag: '反义词',
    },
    {
      id: 'g2q10',
      type: 'judge',
      q: '玩猜人游戏时，可以这样问：Is she helpful?',
      options: ['对', '错'],
      answer: 0,
      explain: '对！猜人时用一般疑问句：Is he/she …? 回答 Yes, he/she is. 或 No, he/she isn\'t.',
      tag: '句型',
    },
  ],
  g3: [
    {
      id: 'g3q1',
      type: 'choice',
      q: '中国的国宝动物，黑白相间、爱吃竹子的是？',
      options: ['panda', 'monkey', 'tiger', 'dog'],
      answer: 0,
      explain: 'panda 大熊猫是中国的国宝，最爱吃竹子 bamboo。',
      tag: '动物',
    },
    {
      id: 'g3q2',
      type: 'choice',
      q: '长着长鼻子和大耳朵的动物是？',
      options: ['elephant', 'panda', 'rabbit', 'penguin'],
      answer: 0,
      explain: 'elephant 大象有长鼻子（long nose）和大耳朵（big ears）。',
      tag: '动物',
    },
    {
      id: 'g3q3',
      type: 'choice',
      q: '「baby elephant」是什么意思？',
      options: ['小象', '象宝宝的食物', '大象的家', '很大的象'],
      answer: 0,
      explain: 'baby 指「幼崽、宝宝」，baby elephant＝小象。',
      tag: '单词',
    },
    {
      id: 'g3q4',
      type: 'choice',
      q: '白白的、住在很冷的地方的熊是？',
      options: ['polar bear', 'panda', 'brown bear', 'teddy bear'],
      answer: 0,
      explain: 'polar bear 北极熊，polar 表示「极地的」，它住在寒冷的北极。',
      tag: '动物',
    },
    {
      id: 'g3q5',
      type: 'choice',
      q: 'Where do polar bears live? 北极熊住在哪里？',
      options: ['In cold places.', 'In hot deserts.', 'In the sea.', 'On farms.'],
      answer: 0,
      explain: '北极熊住在寒冷的地方 in cold places（北极），沙漠和海洋都不对。',
      tag: '常识',
    },
    {
      id: 'g3q6',
      type: 'choice',
      q: '「hometown」是什么意思？',
      options: ['家乡', '家庭作业', '房子', '家谱'],
      answer: 0,
      explain: 'hometown＝家乡（home＋town），My hometown is Shanghai. 我的家乡在上海。',
      tag: '单词',
    },
    {
      id: 'g3q7',
      type: 'choice',
      q: 'The elephant ______ water with its nose. （大象正在玩水）',
      options: ['is playing', 'are playing', 'play', 'played'],
      answer: 0,
      explain: '正在做某事用现在进行时 be＋doing：elephant 是单数用 is playing。',
      tag: '语法',
    },
    {
      id: 'g3q8',
      type: 'judge',
      q: 'Pandas eat bamboo. 大熊猫吃竹子。',
      options: ['对', '错'],
      answer: 0,
      explain: '对！竹子 bamboo 是大熊猫的主食。',
      tag: '常识',
    },
    {
      id: 'g3q9',
      type: 'choice',
      q: 'Elephants in Yunnan 大象在云南旅行时，我们可以怎样保护它们？',
      options: ['Keep away and don\'t feed them.', 'Give them candy.', 'Take them home.', 'Shout at them.'],
      answer: 0,
      explain: '保护野生动物：保持距离、不投喂（keep away and don\'t feed them）。',
      tag: '保护动物',
    },
    {
      id: 'g3q10',
      type: 'choice',
      q: 'Monkeys can ______ trees. （猴子会爬树）',
      options: ['climb', 'swim', 'fly', 'jump'],
      answer: 0,
      explain: '爬树用 climb，climb trees 爬树；swim 游泳，fly 飞。',
      tag: '动词',
    },
  ],
  g4: [
    {
      id: 'g4q1',
      type: 'choice',
      q: '「birthday party」是什么意思？',
      options: ['生日聚会', '生日蛋糕', '生日礼物', '生日歌'],
      answer: 0,
      explain: 'party＝聚会，birthday party 生日聚会。We have a birthday party. 我们开生日会。',
      tag: '单词',
    },
    {
      id: 'g4q2',
      type: 'choice',
      q: '邀请朋友来聚会，要发什么？',
      options: ['an invitation', 'a letter', 'a cake', 'an egg'],
      answer: 0,
      explain: 'invitation＝邀请函，请朋友来参加生日会要写 invitation。',
      tag: '单词',
    },
    {
      id: 'g4q3',
      type: 'choice',
      q: '「share a cake」的意思是？',
      options: ['分享蛋糕', '做一个蛋糕', '买一个蛋糕', '吃光蛋糕'],
      answer: 0,
      explain: 'share＝分享，share a cake 和大家一起分享生日蛋糕。',
      tag: '单词',
    },
    {
      id: 'g4q4',
      type: 'choice',
      q: '过生日时，中国人习惯吃？',
      options: ['noodles', 'rice balls', 'hamburgers', 'ice cream'],
      answer: 0,
      explain: '生日吃长寿面 noodles，It\'s a tradition to eat noodles.（吃面是传统）。',
      tag: '文化',
    },
    {
      id: 'g4q5',
      type: 'choice',
      q: '「letter」是什么意思？',
      options: ['信', '铅笔', '橡皮', '书包'],
      answer: 0,
      explain: 'letter＝信，Letters of love 爱的信，写给家人朋友的信。',
      tag: '单词',
    },
    {
      id: 'g4q6',
      type: 'choice',
      q: '「egg」是什么意思？',
      options: ['蛋', '面包', '牛奶', '苹果'],
      answer: 0,
      explain: 'egg＝蛋、鸡蛋，An egg a day keeps me healthy.（每天一个蛋，健康常相伴）。',
      tag: '单词',
    },
    {
      id: 'g4q7',
      type: 'choice',
      q: 'It\'s a tradition to ______ noodles on birthdays. 括号里填？',
      options: ['eat', 'play', 'drink', 'draw'],
      answer: 0,
      explain: '吃面条用 eat noodles；生日吃长寿面是传统（tradition）。',
      tag: '句型',
    },
    {
      id: 'g4q8',
      type: 'choice',
      q: 'A bowl of birthday noodles 的意思是？',
      options: ['一碗长寿面', '一个生日蛋糕', '一盒鸡蛋', '一碗米饭'],
      answer: 0,
      explain: 'a bowl of 一碗，noodles 面条，合起来是一碗长寿面。',
      tag: '短语',
    },
    {
      id: 'g4q9',
      type: 'judge',
      q: 'We write an invitation to invite friends to our party. 写邀请函可以请朋友来聚会。',
      options: ['对', '错'],
      answer: 0,
      explain: '对！invite＝邀请，邀请函（invitation）就是用来邀请朋友的。',
      tag: '常识',
    },
    {
      id: 'g4q10',
      type: 'choice',
      q: '为小组生日会做计划，Big task 是？',
      options: ['Making a plan for our group birthday party', 'Playing a computer game', 'Watching TV all day', 'Sleeping early'],
      answer: 0,
      explain: '本单元的大任务是制定小组生日会计划：making a plan for our group birthday party。',
      tag: '表达',
    },
  ],
  g5: [
    {
      id: 'g5q1',
      type: 'choice',
      q: '看展览、看老物件，应该去？',
      options: ['museum', 'supermarket', 'playground', 'restaurant'],
      answer: 0,
      explain: 'museum 博物馆，里面陈列文物和老物件，We can see old things in the museum.',
      tag: '场所',
    },
    {
      id: 'g5q2',
      type: 'choice',
      q: '「cinema」是什么地方？',
      options: ['电影院', '公园', '商店', '医院'],
      answer: 0,
      explain: 'cinema＝电影院，We watch films in the cinema. 我们在电影院看电影。',
      tag: '场所',
    },
    {
      id: 'g5q3',
      type: 'choice',
      q: '买食物和日用品，应该去？',
      options: ['supermarket', 'museum', 'bridge', 'park'],
      answer: 0,
      explain: 'supermarket 超市，We buy food in the supermarket. 我们在超市买食品。',
      tag: '场所',
    },
    {
      id: 'g5q4',
      type: 'choice',
      q: '「neighbourhood」的意思是？',
      options: ['社区、街坊', '邻居的名字', '一家商店', '一座桥'],
      answer: 0,
      explain: 'neighbourhood＝社区、街坊，Welcome to my neighbourhood! 欢迎来我的社区！',
      tag: '单词',
    },
    {
      id: 'g5q5',
      type: 'choice',
      q: '过河要走什么？',
      options: ['bridge', 'park', 'shop', 'museum'],
      answer: 0,
      explain: 'bridge＝桥，We cross the river on the bridge. 我们从桥上过河。',
      tag: '单词',
    },
    {
      id: 'g5q6',
      type: 'choice',
      q: 'Is there a park near your home? 的正确回答是？',
      options: ['Yes, there is.', 'Yes, I am.', 'Yes, there are.', 'Yes, it is.'],
      answer: 0,
      explain: 'Is there…? 问「有没有」，回答 Yes, there is. / No, there isn\'t.',
      tag: '句型',
    },
    {
      id: 'g5q7',
      type: 'choice',
      q: 'There ______ two shops in my neighbourhood. 括号里填？',
      options: ['are', 'is', 'am', 'be'],
      answer: 0,
      explain: 'two shops 是复数，用 There are…。',
      tag: '句型',
    },
    {
      id: 'g5q8',
      type: 'choice',
      q: '「Visiting Venice」中的 Venice 是一座？',
      options: ['著名的水城', '中国的高山', '一条大河', '一片森林'],
      answer: 0,
      explain: 'Venice 威尼斯是意大利的著名水城，城里到处是水道和桥。',
      tag: '文化',
    },
    {
      id: 'g5q9',
      type: 'judge',
      q: 'A museum is a place to buy old things. 博物馆是买老物件的地方。',
      options: ['对', '错'],
      answer: 1,
      explain: 'museum 博物馆是看文物、老物件的地方，展品不能买哦；buy 是买，说错啦。',
      tag: '常识',
    },
    {
      id: 'g5q10',
      type: 'choice',
      q: '向朋友介绍自己最喜欢的地方，可以说？',
      options: ['This is a photo of my favourite place.', 'I like apples.', 'He is tall.', 'It is seven o\'clock.'],
      answer: 0,
      explain: '介绍最喜欢的地方：This is a photo of my favourite place. 这是我最喜欢的地方的照片。',
      tag: '表达',
    },
  ],
  g6: [
    {
      id: 'g6q1',
      type: 'choice',
      q: '「autumn」是什么意思？',
      options: ['秋天', '春天', '夏天', '冬天'],
      answer: 0,
      explain: 'autumn＝秋天，美式英语里也常说 fall。',
      tag: '季节',
    },
    {
      id: 'g6q2',
      type: 'choice',
      q: 'Leaves ______ in autumn. （树叶在秋天落下）',
      options: ['fall', 'fly high', 'grow', 'sing'],
      answer: 0,
      explain: 'fall＝落下，Leaves fall in autumn. 树叶秋天飘落。',
      tag: '动词',
    },
    {
      id: 'g6q3',
      type: 'choice',
      q: 'Birds fly ______ in autumn. （鸟儿飞向南方过冬）',
      options: ['south', 'north', 'up', 'down'],
      answer: 0,
      explain: 'fly south 飞往南方，候鸟秋天南下过冬。',
      tag: '短语',
    },
    {
      id: 'g6q4',
      type: 'choice',
      q: '农民伯伯工作的地方是？',
      options: ['farm', 'school', 'museum', 'cinema'],
      answer: 0,
      explain: 'farm＝农场，We pick apples on the farm. 我们在农场摘苹果。',
      tag: '单词',
    },
    {
      id: 'g6q5',
      type: 'choice',
      q: '「fruit」的意思是？',
      options: ['水果', '树叶', '花朵', '蔬菜'],
      answer: 0,
      explain: 'fruit＝水果，Apples are fruit. 苹果是水果。',
      tag: '单词',
    },
    {
      id: 'g6q6',
      type: 'choice',
      q: 'Autumn is a ______ season. （形容秋天凉爽）',
      options: ['cool', 'hot', 'cold', 'warm'],
      answer: 0,
      explain: '秋天气候凉爽，用 cool；hot 炎热，cold 寒冷，warm 温暖。',
      tag: '形容词',
    },
    {
      id: 'g6q7',
      type: 'choice',
      q: '一片树叶是 a leaf，很多片树叶是？',
      options: ['leaves', 'leafs', 'leafes', 'leaf'],
      answer: 0,
      explain: 'leaf 是不规则变化，复数把 f 变 v 加 es：leaves。',
      tag: '名词复数',
    },
    {
      id: 'g6q8',
      type: 'choice',
      q: '夏天（summer）过后是哪个季节？',
      options: ['autumn', 'spring', 'winter', 'summer'],
      answer: 0,
      explain: '季节顺序：spring→summer→autumn→winter，夏天之后是秋天。',
      tag: '季节',
    },
    {
      id: 'g6q9',
      type: 'judge',
      q: 'Apples and pears are fruit. 苹果和梨都是水果。',
      options: ['对', '错'],
      answer: 0,
      explain: '对！苹果、梨都属于水果 fruit。',
      tag: '常识',
    },
    {
      id: 'g6q10',
      type: 'choice',
      q: '本单元的 Big task 是？',
      options: ['Writing a poem for autumn', 'Playing a game', 'Drawing a map', 'Cooking dinner'],
      answer: 0,
      explain: '秋天单元的大任务是写一首秋天的小诗：writing a poem for autumn。',
      tag: '表达',
    },
  ],
  g7: [
    {
      id: 'g7q1',
      type: 'choice',
      q: '「breakfast」是什么意思？',
      options: ['早餐', '午餐', '晚餐', '零食'],
      answer: 0,
      explain: 'breakfast＝早餐，break（打破）＋fast（禁食），睡了一夜，早餐打破饥饿状态。',
      tag: '单词',
    },
    {
      id: 'g7q2',
      type: 'choice',
      q: '面包的英文是？',
      options: ['bread', 'milk', 'rice', 'tea'],
      answer: 0,
      explain: 'bread＝面包，I have bread for breakfast. 我早餐吃面包。',
      tag: '单词',
    },
    {
      id: 'g7q3',
      type: 'choice',
      q: '「juice」是什么意思？',
      options: ['果汁', '水', '汤', '牛奶'],
      answer: 0,
      explain: 'juice＝果汁，orange juice 橙汁，apple juice 苹果汁。',
      tag: '单词',
    },
    {
      id: 'g7q4',
      type: 'choice',
      q: '牛奶的英文是？',
      options: ['milk', 'banana', 'bread', 'egg'],
      answer: 0,
      explain: 'milk＝牛奶，I drink milk every morning. 我每天早上喝牛奶。',
      tag: '单词',
    },
    {
      id: 'g7q5',
      type: 'choice',
      q: '「banana」是什么意思？',
      options: ['香蕉', '苹果', '橘子', '葡萄'],
      answer: 0,
      explain: 'banana＝香蕉，黄色弯弯的水果。',
      tag: '单词',
    },
    {
      id: 'g7q6',
      type: 'choice',
      q: '「healthy」的意思是？',
      options: ['健康的', '好吃的', '昂贵的', '冰的'],
      answer: 0,
      explain: 'healthy＝健康的（health 健康＋y），a healthy breakfast 一顿健康的早餐。',
      tag: '形容词',
    },
    {
      id: 'g7q7',
      type: 'choice',
      q: 'I have bread and milk ______ breakfast. 括号里填？',
      options: ['for', 'at', 'in', 'on'],
      answer: 0,
      explain: '「早餐吃……」用 for breakfast：I have bread and milk for breakfast.',
      tag: '介词',
    },
    {
      id: 'g7q8',
      type: 'choice',
      q: '问别人早餐吃什么，可以问？',
      options: ['What do you have for breakfast?', 'What time is it?', 'Where is your school?', 'Who is he?'],
      answer: 0,
      explain: 'What do you have for breakfast? 你早餐吃什么？回答 I have…。',
      tag: '句型',
    },
    {
      id: 'g7q9',
      type: 'choice',
      q: '下面哪一组是健康的早餐？',
      options: ['Bread, milk and an egg', 'Sweets and cola', 'Chips and ice cream', 'Nothing'],
      answer: 0,
      explain: '面包、牛奶和鸡蛋营养均衡，是健康早餐；糖果、可乐和薯条不健康。',
      tag: '健康',
    },
    {
      id: 'g7q10',
      type: 'judge',
      q: 'Milk is good for us. 牛奶对我们有好处。',
      options: ['对', '错'],
      answer: 0,
      explain: '对！be good for＝对……有好处，牛奶补钙，对身体好。',
      tag: '健康',
    },
  ],
  g8: [
    {
      id: 'g8q1',
      type: 'choice',
      q: '「honest」是什么意思？',
      options: ['诚实的', '懒惰的', '调皮的', '生气的'],
      answer: 0,
      explain: 'honest＝诚实的，an honest child 一个诚实的孩子。',
      tag: '形容词',
    },
    {
      id: 'g8q2',
      type: 'choice',
      q: '「tell the truth」的意思是？',
      options: ['说真话', '讲故事', '说笑话', '喊名字'],
      answer: 0,
      explain: 'truth＝真相，tell the truth＝说真话、讲实话。',
      tag: '短语',
    },
    {
      id: 'g8q3',
      type: 'choice',
      q: '「never tell a lie」的意思是？',
      options: ['从不说谎', '经常讲故事', '从不说话', '总是大笑'],
      answer: 0,
      explain: 'never＝从不，tell a lie＝说谎，合起来是「从不说谎」。',
      tag: '短语',
    },
    {
      id: 'g8q4',
      type: 'choice',
      q: '「keep one\'s word」的意思是？',
      options: ['说话算数、守信', '记单词', '大声说话', '保守秘密'],
      answer: 0,
      explain: 'keep one\'s word＝遵守诺言、说话算数，答应了就要做到。',
      tag: '短语',
    },
    {
      id: 'g8q5',
      type: 'choice',
      q: '借了东西要按时归还，用英语说？',
      options: ['give it back', 'give it up', 'give it out', 'give it away'],
      answer: 0,
      explain: 'give … back＝归还，You should give the book back. 你应该把书还回去。',
      tag: '短语',
    },
    {
      id: 'g8q6',
      type: 'choice',
      q: '不小心打碎了东西，诚实的孩子应该？',
      options: ['tell the truth', 'hide it', 'blame others', 'run away'],
      answer: 0,
      explain: '诚实第一：tell the truth 说真话，主动承认错误。',
      tag: '品格',
    },
    {
      id: 'g8q7',
      type: 'judge',
      q: 'We should keep our word. 我们应该说到做到。',
      options: ['对', '错'],
      answer: 0,
      explain: '对！答应别人的事要做到，这就是诚信（keep our word）。',
      tag: '品格',
    },
    {
      id: 'g8q8',
      type: 'choice',
      q: '「tell a lie」的反义短语是？',
      options: ['tell the truth', 'sing a song', 'play a game', 'make a cake'],
      answer: 0,
      explain: '说谎（tell a lie）的反面是说真话（tell the truth）。',
      tag: '反义',
    },
    {
      id: 'g8q9',
      type: 'choice',
      q: 'She is ______ honest girl. 括号里填？',
      options: ['an', 'a', 'the', '不填'],
      answer: 0,
      explain: 'honest 的 h 不发音，读音以元音开头，所以用 an：an honest girl。',
      tag: '语法',
    },
    {
      id: 'g8q10',
      type: 'choice',
      q: 'My lovely friends 主题里，夸朋友可以选哪句？',
      options: ['You are honest and helpful.', 'You are late again!', 'Give me your pen.', 'Don\'t talk to me.'],
      answer: 0,
      explain: '夸朋友要真诚友好：You are honest and helpful. 你诚实又乐于助人。',
      tag: '表达',
    },
  ],
  g9: [
    {
      id: 'g9q1',
      type: 'choice',
      q: '「It\'s seven o\'clock.」是什么意思？',
      options: ['现在七点整', '现在七点半', '现在差十分七点', '现在七点一刻'],
      answer: 0,
      explain: 'o\'clock 表示「整点」，seven o\'clock＝七点整（7:00）。',
      tag: '时间',
    },
    {
      id: 'g9q2',
      type: 'choice',
      q: '「half past eleven」是几点？',
      options: ['11:30', '11:00', '10:30', '12:30'],
      answer: 0,
      explain: 'half past＋时间＝几点半：half past eleven＝11 点半。',
      tag: '时间',
    },
    {
      id: 'g9q3',
      type: 'choice',
      q: '「ten to four」是几点？',
      options: ['3:50', '4:10', '3:10', '4:50'],
      answer: 0,
      explain: 'ten to four＝差十分四点，也就是 3 点 50 分。to 表示「差几分到几点」。',
      tag: '时间',
    },
    {
      id: 'g9q4',
      type: 'choice',
      q: '「hour hand」指的是钟面上的？',
      options: ['时针', '分针', '秒针', '数字'],
      answer: 0,
      explain: 'hour hand 时针（hour 小时），minute hand 分针（minute 分钟）。',
      tag: '单词',
    },
    {
      id: 'g9q5',
      type: 'choice',
      q: '钟面上又细又长、走得快的针是？',
      options: ['minute hand', 'hour hand', 'big hand', 'small hand'],
      answer: 0,
      explain: 'minute hand 分针又细又长，一小时转一圈；hour hand 时针短粗，走得慢。',
      tag: '常识',
    },
    {
      id: 'g9q6',
      type: 'choice',
      q: '问「现在几点了？」应该说？',
      options: ['What time is it?', 'What day is it?', 'Where is it?', 'How are you?'],
      answer: 0,
      explain: 'What time is it? 问几点，回答 It\'s … o\'clock.',
      tag: '句型',
    },
    {
      id: 'g9q7',
      type: 'choice',
      q: '6:00 用英语说是？',
      options: ['six o\'clock', 'half past six', 'six to six', 'six past six'],
      answer: 0,
      explain: '整点用 数字＋o\'clock：6:00＝six o\'clock。',
      tag: '时间',
    },
    {
      id: 'g9q8',
      type: 'choice',
      q: 'Which hand is short? 钟面上短的针是？',
      options: ['the hour hand', 'the minute hand', 'both hands', 'no hands'],
      answer: 0,
      explain: '时针（hour hand）短而粗，分针（minute hand）长而细。',
      tag: '常识',
    },
    {
      id: 'g9q9',
      type: 'judge',
      q: 'half past seven＝6:30。',
      options: ['对', '错'],
      answer: 1,
      explain: 'half past seven 是七点半：7 点又过半小时，才是 7:30。',
      tag: '时间',
    },
    {
      id: 'g9q10',
      type: 'choice',
      q: '时间棋盘游戏里，你掷出「Move to half past two」，你要走到？',
      options: ['2:30', '2:00', '3:30', '2:15'],
      answer: 0,
      explain: 'half past two＝两点半 2:30。',
      tag: '时间',
    },
  ],
  g10: [
    {
      id: 'g10q1',
      type: 'choice',
      q: '「sunny」是什么意思？',
      options: ['晴朗的', '下雨的', '下雪的', '有雾的'],
      answer: 0,
      explain: 'sunny＝晴朗的（sun 太阳＋ny），Today is sunny. 今天是晴天。',
      tag: '天气',
    },
    {
      id: 'g10q2',
      type: 'choice',
      q: '「rainy」的意思是？',
      options: ['下雨的', '晴朗的', '多云的', '有风的'],
      answer: 0,
      explain: 'rainy＝下雨的（rain 雨＋y），It is rainy today. 今天下雨。',
      tag: '天气',
    },
    {
      id: 'g10q3',
      type: 'choice',
      q: '天上有云，天气是？',
      options: ['cloudy', 'windy', 'sunny', 'snowy'],
      answer: 0,
      explain: 'cloudy＝多云的（cloud 云＋y）。',
      tag: '天气',
    },
    {
      id: 'g10q4',
      type: 'choice',
      q: '树叶在摇、风筝飞得很高，今天天气是？',
      options: ['windy', 'sunny', 'snowy', 'rainy'],
      answer: 0,
      explain: 'windy＝有风的，起风时树叶摇动、风筝好飞。',
      tag: '天气',
    },
    {
      id: 'g10q5',
      type: 'choice',
      q: '「snowy」是什么意思？',
      options: ['下雪的', '下雨的', '晴朗的', '多云的'],
      answer: 0,
      explain: 'snowy＝下雪的（snow 雪＋y），冬天可能下雪 It is snowy in winter.',
      tag: '天气',
    },
    {
      id: 'g10q6',
      type: 'choice',
      q: '「degree」在天气预报里表示？',
      options: ['度（温度单位）', '小时', '公里', '千克'],
      answer: 0,
      explain: 'degree＝度，It is 25 degrees today. 今天 25 度。',
      tag: '单词',
    },
    {
      id: 'g10q7',
      type: 'choice',
      q: '「weather report」的意思是？',
      options: ['天气预报', '新闻联播', '动画片', '体育比赛'],
      answer: 0,
      explain: 'weather report＝天气预报，主持人用它告诉大家明天的天气。',
      tag: '短语',
    },
    {
      id: 'g10q8',
      type: 'choice',
      q: '问「今天天气怎么样？」应该说？',
      options: ['What\'s the weather like today?', 'What time is it?', 'How old are you?', 'What\'s your name?'],
      answer: 0,
      explain: '问天气：What\'s the weather like today? 回答 It\'s sunny/rainy…',
      tag: '句型',
    },
    {
      id: 'g10q9',
      type: 'choice',
      q: 'It is rainy. 出门应该带？',
      options: ['a raincoat', 'sunglasses', 'a kite', 'shorts'],
      answer: 0,
      explain: '下雨带雨衣 raincoat 或雨伞 umbrella。',
      tag: '生活',
    },
    {
      id: 'g10q10',
      type: 'judge',
      q: '播天气预报时可以说：Tomorrow will be sunny and hot.',
      options: ['对', '错'],
      answer: 0,
      explain: '对！will be 表示「将会」，预报明天天气：明天晴朗炎热。',
      tag: '表达',
    },
  ],
}
